version: '3'
services:
  web:
    build: ./
    image: <appname>
    volumes:
      - ~/.ssh/:/root/.ssh/
      - <appname>-sync:/app:nocopy
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: db
      DATABASE_USER: root
      DATABASE_PASSWORD: mypassword
    links:
      - db
      - redis
    command: [bundle, exec, rails, server, --port, '3000', --binding, 0.0.0.0]
    stop_signal: SIGINT
    # For debugging with pry
    # Ref: http://www.chris-kelly.net/2016/07/25/debugging-rails-with-pry-within-a-docker-container/
    tty: true
    stdin_open: true
  jobs:
    build: ./
    image: <appname>
    volumes:
      - ~/.ssh/:/root/.ssh/
      - <appname>-sync:/app:nocopy
    environment:
      DATABASE_HOST: db
      DATABASE_USER: root
      DATABASE_PASSWORD: mypassword
      REDIS_URL=redis://redis:6379
    links:
      - db
      - redis
    command: [bundle, exec, sidekiq]
    # For debugging with pry
    # Ref: http://www.chris-kelly.net/2016/07/25/debugging-rails-with-pry-within-a-docker-container/
    tty: true
    stdin_open: true
  redis:
    image: 'redis:3.2-alpine'
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - './data/redisdata:/var/lib/redis/data'
  db:
    image: postgres:9.5
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data/pgdata
      - ./data/db_dumps:/db_dumps
    environment:
      POSTGRES_PASSWORD: mypassword
      POSTGRES_USER: root
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
volumes:
  <appname>-sync:
    external: true
