version: '3'
services:
  web:
    build: ./
    image: <appname>
    volumes:
      - ~/.ssh/:/root/.ssh/
      - <appname>-sync:/app:rw
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: db
      DATABASE_USER: root
      DATABASE_PASSWORD: mypassword
    links:
      - db
    command: [bundle, exec, rails, server, --port, '3000', --binding, 0.0.0.0]
    stop_signal: SIGINT
    # For debugging with pry
    # Ref: http://www.chris-kelly.net/2016/07/25/debugging-rails-with-pry-within-a-docker-container/
    tty: true
    stdin_open: true
  db:
    image: postgres:9.5
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data/pgdata
      - ./data/db_dumps:/db_dumps
    environment:
      POSTGRES_PASSWORD: mypassword
      POSTGRES_USER: root
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
volumes:
  <appname>-sync:
    external: true
